name: "Meteo.lt Weather"
description: "Integrate Lithuanian weather data from Meteo.lt API into Home Assistant"
version: "0.1.0"
slug: "meteo_lt_weather"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  update_interval: 30
  location: "vilnius"
schema:
  update_interval: int(10,1440)
  location: str
